### ISSUE TITLE
关于源码

### ISSUE THREAD

**Issue by inspurer** [inspurer/WorkAttendanceSystem#1]
有什么问题直接在这问吧，或者加q群861016679

**Comment by Conmi-WhiteJoker** [comment]
大神，好像这个不能部署到ARM架构下，是不是？

**Comment by inspurer** [comment]
没有验证过


 
---原始邮件---
发件人: "conmi"<notifications@github.com&gt;
发送时间: 2020年12月4日 11:33:04
收件人: "inspurer/WorkAttendanceSystem"<WorkAttendanceSystem@noreply.github.com&gt;;
抄送: "月小水长"<2391527690@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [inspurer/WorkAttendanceSystem] 关于源码 (#1)




 
大神，好像这个不能部署到ARM架构下，是不是？

**Comment by Conmi-WhiteJoker** [comment]
> 没有验证过
> […](#)
> ---原始邮件--- 发件人: "conmi"<notifications@github.com&gt; 发送时间: 2020年12月4日 11:33:04 收件人: "inspurer/WorkAttendanceSystem"<WorkAttendanceSystem@noreply.github.com&gt;; 抄送: "月小水长"<2391527690@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [inspurer/WorkAttendanceSystem] 关于源码 (#1) 大神，好像这个不能部署到ARM架构下，是不是？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的

**Comment by Conmi-WhiteJoker** [comment]
windows和树莓派都挂了，这个工具是不是只能运用在linux上？

**Comment by inspurer** [comment]
windows 可以，你环境没配置好

**Comment by Conmi-WhiteJoker** [comment]
pip install -r requirements.txt 全部不行，全部改为最新版之后还是不行~~

**Comment by Conmi-WhiteJoker** [comment]
是不是还要装个cmake和gcc？

**Comment by inspurer** [comment]
嗯嗯，主要是 dlib 安装比较麻烦，可能还要 vs
